#!/bin/sh

# Check that the file being checked actually exists
if [ -f $2 ]; then
	echo "Starting ltest on this file"
elif [ -d $2 ]; then
	echo "Starting ltest on this folder"
else
	echo "This is not a file or folder"
	exit
fi

# Main execution loop, detect if file has changed within the last 2 seconds.
while :
do
	if [ $(expr `date +%s` - `date +%s -r $2`) -lt 2 ]; then
		clear && $1
	fi
	sleep 1
done
